// This file was generated by schema-gen.
// DO NOT EDIT THIS FILE!

//! Golden-test module for Person.

#![allow(clippy::all, missing_docs)]

use serde::{Deserialize, Serialize};

/// A test person.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Person {

    /// Age in years.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub age: Option<u32>,

    /// Primary residence.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub home: Option<Address>,

    /// Current mood.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub mood: Option<String>,

    /// Full name.
    pub name: String,

    /// Arbitrary tags.
    #[serde(skip_serializing_if = "Vec::is_empty", default = "default_person_tags")]
    pub tags: Vec<String>,

    /// Schema version.
    #[serde(skip_serializing_if = "skip_if_person_version", default)]
    pub version: Option<i64>,

    /// Origin URI when decoded from a file.
    #[serde(skip)]
    pub source_uri: Option<String>,

    /// Extension-specific data.
    #[serde(default, skip_serializing_if = "std::collections::HashMap::is_empty")]
    pub extensions: std::collections::HashMap<String, serde_json::Value>,

    /// Application-specific data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<serde_json::Value>,
}

fn default_person_tags() -> Vec<String> { vec![] }

impl Default for Person {
    fn default() -> Self {
        Self {
            age: Default::default(),
            home: Default::default(),
            mood: Default::default(),
            name: Default::default(),
            tags: default_person_tags(),
            version: Default::default(),
            source_uri: Default::default(),
            extensions: Default::default(),
            extras: Default::default(),
        }
    }
}

fn skip_if_person_version(v: &Option<i64>) -> bool { *v == 0 }

